### ISSUE TITLE
Allow to resolve issues in security groups.

### ISSUE THREAD

**Issue by dmitrykrivaltsevich** [zalando-stups/fullstop-cli#4]
At the moment `-m` parameter supports only key=value pairs and doesn't allow to specify an array of values. Would be good to have an ability to resolve issues like this:

``` json
{
        "account_id": "XXXX",
        "comment": null,
        "created_time": 1460509787.801,
        "instance_id": "i-f4...8",
        "meta_info": "errorMessages: [Unsecured security group! Only ports 80 and 443 are allowed], unsecuredSecurityGroups: [sg-XXXX]",
        "region": "eu-west-1",
        "violation_type": "UNSECURED_PUBLIC_ENDPOINT"
}
```

**Comment by hjacobs** [comment]
@dmitrykrivaltsevich the "meta_info" should now always be a JSON object (map/dict), old violations might have a different format (just a string). We don't plan to support the old violation "meta_info" formats.

**Comment by hjacobs** [comment]
@Gregsen @mrandi can you check? Apparently the "created" time stamp is recent...

**Comment by Gregsen** [comment]
What exactly do you mean by array? I think you can resolve several key value pairs:

`-m key=value, key=value, ...`

**Comment by dmitrykrivaltsevich** [comment]
@Gregsen , in my example I have 

```
 "meta_info": "errorMessages: [Unsecured security group! Only ports 80 and 443 are allowed], unsecuredSecurityGroups: [sg-XXXX]"
```

and this violation can not be resolved via following command:

``` sh
$ fullstop resolve-violations --accounts XXXXXXXX -m unsecuredSecurityGroups=sg-XXXX
```

because here I need somehow to specify an array of security group names.

**Comment by prayerslayer** [comment]
Please don't post any IDs (security groups, accounts) on github.com.

**Comment by dmitrykrivaltsevich** [comment]
@prayerslayer , just erased from comments

**Comment by hjacobs** [comment]
@dmitrykrivaltsevich OK, now I understand your problem :smile:

**Comment by hjacobs** [comment]
@dmitrykrivaltsevich works right now with the right syntax as we convert the value to string:

```
fullstop resolve -t UNSECURED_PUBLIC_ENDPOINT -m "unsecuredSecurityGroups=['sg-fb123']" '... whatever ...'
```

**Comment by dmitrykrivaltsevich** [comment]
@hjacobs thank you! it works
