### ISSUE TITLE
Feature: ability to use regex/wildcards in the -m option

### ISSUE THREAD

**Issue by sina-golesorkhi** [zalando-stups/fullstop-cli#9]
Hi,

I think it not supported for now that I give the following command:
`fullstop list-violations -s 100d -l 1000 -m deployment_artifact=*partOfMyAppName*`

and the value of this KEY=VALUE is the exact match currently.
The problem that I have is that not all violations return a value for application_id and I have to go after the deployment_artifact in order to filter for my app_id

Thanks.

**Comment by harti2006** [comment]
I think this use case is already supported.
Please have a look at the option: `-x, --remeta REGEX Filter by meta info by regular expression`

**Comment by sina-golesorkhi** [comment]
@harti2006 Thanks. I was running on version 1.0.20 and the option was not available there ;)
